# Definition
stages:
    - build
    - test

# Build
build:
    stage: build
    tags:
        - dalfcs_docker_kvm
    script: 
        - cd back-end
        - mvn clean package -DskipTests=true

# Test
test:
    stage: test
    tags: 
        - dalfcs_docker_kvm
    script:
        - cd back-end
        - mvn clean verify 

