# Defination
stages:
    - build
    - test

# Build
build:
    stage: build
    tags:
        - ugrad
    script: 
        mvn clean package -DskipTests=true

# Test
test:
    stage: test
    tags: 
        - ugrad
    script:
        mvn clean verify 

